#LOAD THEME
theme: jekyll-theme-minimal

#BASICS
title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: false
avatar: "/images/i3.png"
round-avatar: true
