#LOAD THEME
theme: jekyll-theme-minimal

#BASICS
title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
author: Some Person
show_downloads: false

#COLORS
navbar-col: "#F5F5F5"
navbar-text-col: "#404040"
navbar-border-col: "#EAEAEA"
page-col: "#000000"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#F5F5F5"
footer-text-col: "#777777"
footer-link-col: "#404040"
